oprt1=float (input("Enter the first operator in decimal "))
oprt2=float(input("Enter the second operator in decimal "))

print("the addition of these two numbers is:   ",oprt1+oprt2)
print("the subtraction of these two numbers is:   ",oprt1-oprt2)
print("the multiplication of these two numbers is:   ",oprt1*oprt2)
print("the division of these two numbers is:   ",oprt1/oprt2)
print("the floor division of these two numbers is:   ",oprt1//oprt2)
print("the power of these two numbers is:   ",oprt1**oprt2)
print("the rimainder of these two numbers is:   ",oprt1%oprt2)
